# Generated by Django 5.2.6 on 2026-06-13 04:55

import apps.newsletter.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('unsubscribed', 'Dado de baja')], default='pending', max_length=12, verbose_name='Estado')),
                ('token', models.CharField(default=apps.newsletter.models.generate_token, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('confirmed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
                'ordering': ['-created_at'],
            },
        ),
    ]
