# Generated by Django 5.2.6 on 2026-06-13 04:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Página genérica',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introducción')),
                ('hero_cta_text', models.CharField(blank=True, max_length=80, verbose_name='Texto del botón principal')),
                ('hero_cta_link', models.URLField(blank=True, verbose_name='Enlace del botón')),
            ],
            options={
                'verbose_name': 'Página de inicio',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Eslogan')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter / X')),
                ('mastodon_url', models.URLField(blank=True, verbose_name='Mastodon')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('footer_text', wagtail.fields.RichTextField(blank=True, verbose_name='Texto del pie')),
            ],
            options={
                'verbose_name': 'Ajustes del sitio',
            },
        ),
    ]
