# Generated by Django 5.2.6 on 2026-06-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.CharField(blank=True, help_text='URL absoluta o ruta interna (p. ej. /blog/).', max_length=255, verbose_name='Enlace del botón'),
        ),
    ]
