# Generated by Django 5.2.6 on 2026-06-13 04:55

import django.db.models.deletion
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=255, verbose_name='Introducción')),
            ],
            options={
                'verbose_name': 'Índice del blog',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('color', models.CharField(default='indigo', max_length=20, verbose_name='Color de acento')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('excerpt', models.TextField(blank=True, help_text='Resumen breve para listados y SEO.', max_length=400, verbose_name='Extracto')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('code', 5), ('callout', 9), ('image', 13), ('quote', 16), ('embed', 17), ('table', 18)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Encabezado'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote', 'code', 'document-link'], 'icon': 'pilcrow', 'label': 'Párrafo'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Texto plano'), ('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('bash', 'Bash / Shell'), ('go', 'Go'), ('rust', 'Rust'), ('c', 'C'), ('cpp', 'C++'), ('java', 'Java'), ('php', 'PHP'), ('ruby', 'Ruby'), ('sql', 'SQL'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON'), ('yaml', 'YAML'), ('dockerfile', 'Dockerfile'), ('nginx', 'Nginx'), ('diff', 'Diff')], 'label': 'Lenguaje'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Título / nombre de archivo', 'required': False}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Código'}), 5: ('wagtail.blocks.StructBlock', [[('language', 2), ('caption', 3), ('code', 4)]], {}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('danger', 'Peligro / Seguridad')], 'label': 'Estilo'}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code'], 'label': 'Contenido'}), 9: ('wagtail.blocks.StructBlock', [[('style', 6), ('title', 7), ('body', 8)]], {}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen'}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Pie de foto', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Texto alternativo (accesibilidad)', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('image', 10), ('caption', 11), ('alt_text', 12)]], {}), 14: ('wagtail.blocks.TextBlock', (), {'label': 'Cita'}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Autor de la cita', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('quote', 14), ('attribution', 15)]], {}), 17: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'Embed (YouTube, gist, etc.)'}), 18: ('wagtail.blocks.RawHTMLBlock', (), {'icon': 'table', 'label': 'HTML/tabla (avanzado)', 'required': False})}, verbose_name='Cuerpo')),
                ('reading_time', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Tiempo de lectura (min)')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Permitir comentarios')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen de portada')),
            ],
            options={
                'verbose_name': 'Artículo',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.articlepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.ArticleTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Avatar')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.author', verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.category', verbose_name='Categoría'),
        ),
    ]
